# Generated by Django 4.2.3 on 2025-11-26 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('nome', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('password_hash', models.CharField(max_length=512)),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=512)),
                ('descricao', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('capa', models.BinaryField()),
                ('generos', models.ManyToManyField(related_name='filmes', to='api.genero')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('visto', models.BooleanField(default=False)),
                ('favorito', models.BooleanField(default=False)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.filme')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'unique_together': {('filme', 'usuario')},
            },
        ),
    ]
