# Generated by Django 5.2.8 on 2025-11-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='poster_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
