# Generated by Django 5.2.8 on 2025-12-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_filme_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeusuario',
            name='ver_mais_tarde',
            field=models.BooleanField(default=False),
        ),
    ]
