# Generated by Django 5.2.8 on 2025-12-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_atividadeusuario_ver_mais_tarde'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeusuario',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
