# Generated by Django 6.0 on 2025-12-10 00:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fix_filme_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(help_text='Classificação do filme (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(blank=True, help_text='Comentário/review detalhado', null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da avaliação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True, help_text='Data e hora de adição aos favoritos')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de apresentação na lista (0 = recente primeiro)')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-data_adicao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoVisualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visualizacao', models.DateTimeField(auto_now_add=True, help_text='Data e hora da visualização')),
                ('minuto_parado', models.IntegerField(blank=True, help_text='Minuto em que o utilizador parou (para funcionalidades futuras)', null=True)),
                ('completo', models.BooleanField(default=True, help_text='Se o filme foi visualizado completamente')),
            ],
            options={
                'verbose_name': 'Histórico de Visualização',
                'verbose_name_plural': 'Históricos de Visualização',
                'ordering': ['-data_visualizacao'],
            },
        ),
        migrations.AlterModelOptions(
            name='atividadeusuario',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Atividade de Utilizador', 'verbose_name_plural': 'Atividades de Utilizadores'},
        ),
        migrations.AlterModelOptions(
            name='filme',
            options={'ordering': ['-created_at'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nome'], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-created_at'], 'verbose_name': 'Utilizador', 'verbose_name_plural': 'Utilizadores'},
        ),
        migrations.AlterUniqueTogether(
            name='atividadeusuario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='filme',
            name='rating',
        ),
        migrations.AddField(
            model_name='filme',
            name='rating_tmdb',
            field=models.FloatField(blank=True, help_text='Rating do filme na TMDB (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='atividadeusuario',
            name='favorito',
            field=models.BooleanField(default=False, help_text='Marcado como favorito'),
        ),
        migrations.AlterField(
            model_name='atividadeusuario',
            name='filme',
            field=models.ForeignKey(help_text='Filme alvo da atividade', on_delete=django.db.models.deletion.CASCADE, related_name='atividades_usuarios', to='api.filme'),
        ),
        migrations.AlterField(
            model_name='atividadeusuario',
            name='rating',
            field=models.SmallIntegerField(blank=True, help_text='Avaliação do utilizador (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='atividadeusuario',
            name='review',
            field=models.TextField(blank=True, help_text='Comentário/review do utilizador sobre o filme', null=True),
        ),
        migrations.AlterField(
            model_name='atividadeusuario',
            name='usuario',
            field=models.ForeignKey(help_text='Utilizador que realizou a atividade', on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='atividadeusuario',
            name='ver_mais_tarde',
            field=models.BooleanField(default=False, help_text="Adicionado à lista 'Ver Mais Tarde' (watchlist)"),
        ),
        migrations.AlterField(
            model_name='atividadeusuario',
            name='visto',
            field=models.BooleanField(default=False, help_text='Marcado como visto pelo utilizador'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='capa',
            field=models.BinaryField(blank=True, help_text='Imagem da capa em formato binário', null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='descricao',
            field=models.TextField(blank=True, help_text='Sinopse ou descrição detalhada do filme', null=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='generos',
            field=models.ManyToManyField(help_text='Géneros associados ao filme', related_name='filmes', to='api.genero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='nome',
            field=models.CharField(help_text='Título do filme', max_length=512),
        ),
        migrations.AlterField(
            model_name='filme',
            name='poster_path',
            field=models.CharField(blank=True, help_text='Caminho/URL do poster na TMDB', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do género', null=True),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(help_text='Nome do género (único)', max_length=512, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da conta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Email único para autenticação', max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(help_text='Nome completo do utilizador', max_length=512),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password_hash',
            field=models.CharField(help_text='Password hasheada com algoritmo do Django', max_length=512),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização'),
        ),
        migrations.AlterUniqueTogether(
            name='atividadeusuario',
            unique_together={('usuario', 'filme')},
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['usuario', 'favorito'], name='api_ativida_usuario_35cc9e_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['usuario', 'visto'], name='api_ativida_usuario_f59a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['usuario', 'rating'], name='api_ativida_usuario_955250_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['usuario', 'ver_mais_tarde'], name='api_ativida_usuario_83bdda_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['filme', 'rating'], name='api_ativida_filme_i_39bf38_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeusuario',
            index=models.Index(fields=['-updated_at'], name='api_ativida_updated_a44216_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['nome'], name='api_filme_nome_796cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['-rating_tmdb'], name='api_filme_rating__5262a9_idx'),
        ),
        migrations.AddIndex(
            model_name='filme',
            index=models.Index(fields=['-created_at'], name='api_filme_created_cb6444_idx'),
        ),
        migrations.AddIndex(
            model_name='genero',
            index=models.Index(fields=['nome'], name='api_genero_nome_5652a1_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='api_usuario_email_30f64d_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['-created_at'], name='api_usuario_created_59ff90_idx'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='filme',
            field=models.ForeignKey(help_text='Filme avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.filme'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='usuario',
            field=models.ForeignKey(help_text='Utilizador que avaliou', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='filme',
            field=models.ForeignKey(help_text='Filme marcado como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='api.filme'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='usuario',
            field=models.ForeignKey(help_text='Utilizador que marcou como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='historicovisualizacao',
            name='filme',
            field=models.ForeignKey(help_text='Filme visualizado', on_delete=django.db.models.deletion.CASCADE, related_name='visualizacoes', to='api.filme'),
        ),
        migrations.AddField(
            model_name='historicovisualizacao',
            name='usuario',
            field=models.ForeignKey(help_text='Utilizador que visualizou', on_delete=django.db.models.deletion.CASCADE, related_name='historico_visualizacoes', to='api.usuario'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['usuario', 'rating'], name='api_avaliac_usuario_4aeccc_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['filme', 'rating'], name='api_avaliac_filme_i_c30b88_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['-data_avaliacao'], name='api_avaliac_data_av_f77773_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('usuario', 'filme')},
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['usuario', '-data_adicao'], name='api_favorit_usuario_7eff00_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['filme'], name='api_favorit_filme_i_015bdb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'filme')},
        ),
        migrations.AddIndex(
            model_name='historicovisualizacao',
            index=models.Index(fields=['usuario', '-data_visualizacao'], name='api_histori_usuario_cf4c58_idx'),
        ),
        migrations.AddIndex(
            model_name='historicovisualizacao',
            index=models.Index(fields=['filme', '-data_visualizacao'], name='api_histori_filme_i_19a2f6_idx'),
        ),
    ]
